---
? ''
: - ttl: 300
    type: A
    value: 157.245.58.28
  - ttl: 1800
    type: NS
    values:
    - ns1.digitalocean.com.
    - ns2.digitalocean.com.
    - ns3.digitalocean.com.
www:
  ttl: 300
  type: A
  value: 157.245.58.28
